### ISSUE TITLE
Changing background image

### ISSUE THREAD

**Issue by garyrompz** [matteocourthoud/custom-wowchemy-settings#1]
Thanks for sharing this! How do you change the mountain background image? Which file do you edit and where do you add the image? Thanks!

**Comment by oameye** [comment]
Also interested in the answer here! :D

**Comment by oameye** [comment]
@garyrompz add the following code to you `about` widget page in`content\home\about.md

```YAML
design:
  background:
    # Name of image in `assets/media/`.
    image: mountains.jpg
    # Darken the image? Range 0-1 where 0 is transparent and 1 is opaque.
    image_darken: 1
    #  Options are `cover` (default), `contain`, or `actual` size.
    image_size: contain
    # Options include `left`, `center` (default), or `right`.
    image_position: bottom
    # Use a fun parallax-like fixed background effect on desktop? true/false
    image_parallax: false
    # Text color (true=light, false=dark, or remove for the dynamic theme color).
    text_color_light: false
```
![mountains](https://user-images.githubusercontent.com/57623933/159658259-54521083-0e33-4ccc-bfb4-fed84ee03fd2.jpg)
